# Generated by Django 6.0.8 on 2026-10-04 12:20

import django.db.models.deletion
import django.utils.timezone
import djangospice.db.mixins
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('django_app', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('installing', 'Installing'), ('installed', 'Installed'), ('updating', 'Updating'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('uninstalling', 'Uninstalling')], default='discovered', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('key',),
                'indexes': [models.Index(fields=['status'], name='app_registr_status_63bd52_idx'), models.Index(fields=['enabled'], name='app_registr_enabled_06714d_idx')],
            },
            bases=(djangospice.db.mixins.SerializesModels, models.Model),
        ),
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('register', 'Register'), ('install', 'Install'), ('update', 'Update'), ('enable', 'Enable'), ('disable', 'Disable'), ('uninstall', 'Uninstall'), ('rollback', 'Rollback')], max_length=30)),
                ('successful', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_history', to='app_registry.appinstance')),
            ],
            options={
                'ordering': ('-started_at',),
            },
            bases=(djangospice.db.mixins.SerializesModels, models.Model),
        ),
        migrations.CreateModel(
            name='AppDependency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_key', models.CharField(max_length=100)),
                ('version_specifier', models.CharField(blank=True, max_length=100)),
                ('optional', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='app_registry.appinstance')),
            ],
            options={
                'ordering': ('dependency_key',),
                'constraints': [models.UniqueConstraint(fields=('app', 'dependency_key'), name='unique_app_dependency')],
            },
            bases=(djangospice.db.mixins.SerializesModels, models.Model),
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_records', to='app_registry.appinstance')),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_permission', to='auth.permission')),
            ],
            options={
                'ordering': ('app__key', 'permission__codename'),
                'constraints': [models.UniqueConstraint(fields=('app', 'permission'), name='unique_app_permission')],
            },
            bases=(djangospice.db.mixins.SerializesModels, models.Model),
        ),
    ]
